# Generated by Django 4.1.5 on 2023-01-07 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=100)),
                ('state', models.CharField(default='stop', max_length=16)),
                ('next_state', models.CharField(default='stop', max_length=16)),
            ],
        ),
    ]
